name: audio_engagement_analytics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=23.0
  - boto3>=1.26.0
  - pandas>=2.0.0
  - numpy>=1.24.0
  - python-dotenv>=1.0.0
  - pytest>=7.3.1
  - black>=23.3.0
  - flake8>=6.0.0
  - dash>=2.9.0
  - plotly>=5.13.0
  - pyarrow>=12.0.1
  - awscli>=1.27.0
  - jupyter
  - ipykernel 